### ISSUE TITLE
ARM OSX Migrator?

### ISSUE THREAD

**Issue by holymonson** [conda-forge/bpython-feedstock#22]
### Comment:

@conda-forge/help-osx-arm64 Hi, may I ask why OSX Arm Migration bot doesn't run against `bpython`? It seems missing in https://conda-forge.org/status/#armosxaddition.

**Comment by xhochy** [comment]
You need to add it to the list of packages here: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt
